version: "3"

services:
  app:
    build: .
    env_file: .env
    command:
      - /bin/shawty
      - -database
      - /data/shawty.db
      - -admin-user
      - $ADMIN_USER
      - -admin-password
      - $ADMIN_PASSWORD
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
    restart: unless-stopped
